class DomainError(BaseException): ...


class InvalidLengthError(DomainError): ...


class InvalidRoleError(DomainError): ...


class UserAlreadyExistsError(DomainError): ...


class UserNotFoundError(DomainError): ...


class InvalidProviderError(DomainError): ...


class InvalidProviderUserIdError(DomainError): ...
