class DomainError(BaseException): ...


class InvalidLengthError(DomainError): ...


class InvalidRoleError(DomainError): ...


class UserAlreadyExistsError(DomainError): ...


class UserNotFoundError(DomainError): ...


class InvalidAuthProviderError(DomainError): ...


class InvalidAuthProviderUserIdError(DomainError): ...


class AuthProviderAccountAlreadyInUseError(DomainError): ...


class AuthProviderNotLinkedError(DomainError): ...


class AuthProviderUnlinkNotSafeError(DomainError): ...
