"""add auth accounts table

Revision ID: b54ff70c111e
Revises: ad13f8cd35d9
Create Date: 2026-03-23 19:27:11.892681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54ff70c111e'
down_revision: Union[str, Sequence[str], None] = 'ad13f8cd35d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_accounts',
    sa.Column('auth_account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auth_provider', sa.String(length=255), nullable=False),
    sa.Column('auth_provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('auth_account_id')
    )
    #op.alter_column('users', 'user_id',
    #           existing_type=sa.NUMERIC(),
    #           type_=sa.UUID(),
    #           existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('users', 'user_id',
    #           existing_type=sa.UUID(),
    #           type_=sa.NUMERIC(),
    #           existing_nullable=False)
    op.drop_table('auth_accounts')
    # ### end Alembic commands ###
