name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            backend:
              - 'src/backend/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: astral-sh/setup-uv@v7.3.0
      - run: uv python install
      - run: uv sync
      - run: uv run pytest
        env:
          TEST_MODE: "true"
